# Generated by Django 6.0.3 on 2026-03-20 16:34

import apps.users.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import shared.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='countries',
            name='flag',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/avatar', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blitz_rating',
            field=models.PositiveIntegerField(db_index=True, default=1200, verbose_name='blitz rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blitz_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='blitz rating updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bullet_rating',
            field=models.PositiveIntegerField(db_index=True, default=1200, verbose_name='bullet rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bullet_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='bullet rating updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='chat id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=apps.users.models.Countries.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='users.countries', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number is not valid! Please, enter a valid phone number in the format "+998XXXXXXXXX".', regex='^\\+998\\d{9}$')], verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rapid_rating',
            field=models.PositiveIntegerField(db_index=True, default=1200, verbose_name='rapid rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rapid_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='rapid rating updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, validators=[shared.django.validate_telegram_username, django.core.validators.MinLengthValidator(5)], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_username_lower', violation_error_message='User with this username already exists!'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), fields=('phone_number',), name='unique_phone_number_not_blank_or_null', violation_error_message='This phone number is already in use!'),
        ),
    ]
