# Generated by Django 6.0.3 on 2026-03-20 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonym_token', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0)),
                ('was_failed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=1600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Connection History',
                'verbose_name_plural': 'Connection Histories',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Matchmaking'), (1, 'Private'), (2, 'Tournament')])),
                ('fen', models.CharField(blank=True, max_length=200, null=True)),
                ('turn', models.PositiveIntegerField(blank=True, null=True)),
                ('history', models.TextField(blank=True, help_text='JSON string of move history. TextField because PostgreSQL jsonb sorts keys alphabetically, which breaks move order.', null=True)),
                ('last_move', models.JSONField(blank=True, default=list, null=True)),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('color_win', models.PositiveIntegerField(blank=True, null=True)),
                ('all_players_left', models.BooleanField(default=False)),
                ('initial_time_white', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
                ('initial_time_black', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
                ('remaining_time_white', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
                ('remaining_time_black', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
                ('increment', models.PositiveIntegerField(default=0, help_text='Seconds per move')),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
                ('captured_pieces_count_by_white', models.PositiveIntegerField(default=0)),
                ('captured_pieces_count_by_black', models.PositiveIntegerField(default=0)),
                ('first_color_first_move_done', models.BooleanField(default=False)),
                ('second_color_first_move_done', models.BooleanField(default=False)),
                ('first_move_check_task_id', models.UUIDField(blank=True, null=True)),
                ('first_move_check_task_time', models.DateTimeField(blank=True, null=True)),
                ('move_check_task_id', models.UUIDField(blank=True, null=True)),
                ('white_draw_offer', models.BooleanField(default=False)),
                ('black_draw_offer', models.BooleanField(default=False)),
                ('rating_calculated', models.BooleanField(default=False)),
                ('private_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('separate_var', models.CharField(help_text='Variable name for rating field: bullet, blitz, rapid', max_length=20, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='game_types/')),
            ],
            options={
                'verbose_name': 'Game Type',
                'verbose_name_plural': 'Game Types',
            },
        ),
        migrations.CreateModel(
            name='GameTypesTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Display name, e.g. '5+3'", max_length=20)),
                ('time', models.IntegerField(help_text='Initial time in seconds')),
                ('increment', models.IntegerField(default=0, help_text='Increment per move in seconds')),
            ],
            options={
                'verbose_name': 'Time Control',
                'verbose_name_plural': 'Time Controls',
                'ordering': ['type', 'time', 'increment'],
            },
        ),
    ]
