# Generated by Django 6.0.3 on 2026-03-20 05:47

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='authorized_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='guest_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.connectionhistory'),
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='black_anonym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to='game.connectionhistory'),
        ),
        migrations.AddField(
            model_name='game',
            name='created_by_anonym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='game.connectionhistory'),
        ),
        migrations.AddField(
            model_name='game',
            name='created_by_authorized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='white_anonym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to='game.connectionhistory'),
        ),
        migrations.AddField(
            model_name='chat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='game.game'),
        ),
        migrations.AddField(
            model_name='gametypestime',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_controls', to='game.gametypes'),
        ),
        migrations.AddField(
            model_name='game',
            name='type_of_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game.gametypestime'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorized_sender__isnull', True), ('guest_sender__isnull', False)), models.Q(('authorized_sender__isnull', False), ('guest_sender__isnull', True)), _connector='OR'), name='game_chat_sender_xor'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['has_ended', 'has_started'], name='game_game_has_end_02ca11_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white', 'has_ended'], name='game_game_white_i_e0b744_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black', 'has_ended'], name='game_game_black_i_9efcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['tree_id', 'lft'], name='game_game_tree_id_lft_idx'),
        ),
    ]
