# Generated by Django 6.0.3 on 2026-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='remaining_time_black',
            field=models.FloatField(blank=True, help_text='Seconds (float for precision)', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='remaining_time_white',
            field=models.FloatField(blank=True, help_text='Seconds (float for precision)', null=True),
        ),
    ]
