# Generated by Django 6.0.3 on 2026-03-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_align_game_types_with_v1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametypes',
            options={'ordering': ['title'], 'verbose_name': 'Game Type', 'verbose_name_plural': 'Game Types'},
        ),
    ]
